# Generated by Django 2.2 on 2020-08-10 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='webapp.Types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(default='task', max_length=10),
        ),
    ]
