# Generated by Django 2.2 on 2020-08-10 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200810_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
