# Generated by Django 2.2 on 2020-08-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200810_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='status', to='webapp.Status', verbose_name='Статус'),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='type',
        ),
        migrations.AddField(
            model_name='tasks',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='types', to='webapp.Types', verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='types',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Тип'),
        ),
    ]
