# Generated by Django 2.2 on 2020-08-13 13:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200811_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание'),
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='status',
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='webapp.Status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='summary',
            field=models.CharField(max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Задача'),
        ),
    ]
