# Generated by Django 2.2 on 2020-08-17 07:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200813_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время обновления'),
        ),
    ]
