# Generated by Django 2.2 on 2020-08-17 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_tasks_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Время обновления'),
        ),
    ]
