# Generated by Django 2.2 on 2020-08-27 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20200817_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, verbose_name='Начало проекта')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Конец проекта')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.ProhibitNullCharactersValidator()], verbose_name='Название:')),
                ('description', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(15)], verbose_name='Описание')),
            ],
        ),
    ]
