# Generated by Django 2.2 on 2020-08-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ManyToManyField(blank=True, related_name='project', to='webapp.Projects', verbose_name='Проект'),
        ),
    ]
