# Generated by Django 2.2 on 2020-08-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_tasks_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
