# Generated by Django 2.2 on 2020-09-10 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200903_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='project',
        ),
        migrations.AddField(
            model_name='tasks',
            name='project',
            field=models.ManyToManyField(null=True, related_name='project', to='webapp.Projects', verbose_name='Проект'),
        ),
    ]
