# Generated by Django 2.2 on 2020-09-10 10:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0014_auto_20200910_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='users',
        ),
        migrations.AddField(
            model_name='projects',
            name='users',
            field=models.ManyToManyField(related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
