# Generated by Django 2.2 on 2020-09-14 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20200910_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'permissions': [('can_change_group', 'Может изменять состав группы')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
